In [1]:
import pandas as pd
import os

In [2]:
tickets_path = "../data/files/01_support_tickets.csv"
transactions_path = "../data/files/02_transactions.csv"

tickets = pd.read_csv(tickets_path)
transactions = pd.read_csv(transactions_path)

In [3]:
tickets.head()

,ticket_id,date_created,customer_id,channel,category,sub_category,query_text,sentiment,risk_level,resolution_text,resolution_time_minutes,resolved_by,customer_satisfaction,escalated
0,TKT-10001,2023-03-13,CUST872246,Web Chat,Fraud/Unauthorized,I see a transaction of ₹{amt} I didn't m,I see a transaction of ₹999 I didn't make on 2...,Urgent,High,Unauthorized transaction reported on account. ...,28,Sneha R.,2,Yes
1,TKT-10002,2023-11-05,CUST127824,Branch,Fraud/Unauthorized,I see a transaction of ₹{amt} I didn't m,I see a transaction of ₹500 I didn't make on 1...,Neutral,High,Unauthorized transaction reported on account. ...,27,Auto-Resolved,5,No
2,TKT-10003,2023-08-05,CUST456778,Phone,Fraud/Unauthorized,I see a transaction of ₹{amt} I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Neutral,High,Unauthorized transaction reported on account. ...,11,Anjali K.,2,No
3,TKT-10004,2023-01-23,CUST865179,Email,Fraud/Unauthorized,I see a transaction of ₹{amt} I didn't m,I see a transaction of ₹999 I didn't make on 1...,Confused,High,Unauthorized transaction reported on account. ...,8,Vikram P.,2,Yes
4,TKT-10005,2023-12-05,CUST338968,Phone,Fraud/Unauthorized,I see a transaction of ₹{amt} I didn't m,"I see a transaction of ₹25,000 I didn't make o...",Frustrated,High,Unauthorized transaction reported on account. ...,12,Priya S.,5,No

In [4]:
tickets.shape

(200, 14)

In [5]:
tickets.columns

Index(['ticket_id', 'date_created', 'customer_id', 'channel', 'category',
       'sub_category', 'query_text', 'sentiment', 'risk_level',
       'resolution_text', 'resolution_time_minutes', 'resolved_by',
       'customer_satisfaction', 'escalated'],
      dtype='str')

In [6]:
tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ticket_id                200 non-null    str
 1   date_created             200 non-null    str
 2   customer_id              200 non-null    str
 3   channel                  200 non-null    str
 4   category                 200 non-null    str
 5   sub_category             200 non-null    str
 6   query_text               200 non-null    str
 7   sentiment                200 non-null    str
 8   risk_level               200 non-null    str
 9   resolution_text          200 non-null    str
 10  resolution_time_minutes  200 non-null    int64
 11  resolved_by              200 non-null    str
 12  customer_satisfaction    200 non-null    int64
 13  escalated                200 non-null    str
dtypes: int64(2), str(12)
memory usage: 78.6 KB

In [7]:
tickets.isnull().sum()

ticket_id                  0
date_created               0
customer_id                0
channel                    0
category                   0
sub_category               0
query_text                 0
sentiment                  0
risk_level                 0
resolution_text            0
resolution_time_minutes    0
resolved_by                0
customer_satisfaction      0
escalated                  0
dtype: int64

In [8]:
transactions.head()

,transaction_id,account_id,timestamp,amount_inr,merchant_name,merchant_category,transaction_type,city,hour_of_day,day_of_week,is_international,velocity_flag,geo_anomaly_flag,high_amount_flag,fraud_label,fraud_reason
0,TXN500001,ACC995993,2023-05-21 01:35:00,7553.61,Flipkart,E-commerce,Credit Card,Mumbai,1,Sunday,No,No,No,No,0,NaN
1,TXN500002,ACC163182,2023-09-26 10:44:00,634.78,Zomato,Food Delivery,Credit Card,Chennai,10,Tuesday,No,No,No,No,0,NaN
2,TXN500003,ACC107161,2023-08-26 01:35:00,1136.71,Zomato,Food Delivery,UPI,Hyderabad,1,Saturday,No,No,No,No,0,NaN
3,TXN500004,ACC103642,2023-07-09 02:34:00,41478.01,VPN_Service_Anon,Digital,UPI,Dubai,2,Sunday,Yes,Yes,Yes,Yes,1,Off-hours
4,TXN500005,ACC218118,2023-04-07 18:46:00,1139.76,Ola Cabs,Transport,Debit Card,Chennai,18,Friday,No,No,No,No,0,NaN

In [9]:
transactions.shape

(2000, 16)

In [10]:
transactions.columns

Index(['transaction_id', 'account_id', 'timestamp', 'amount_inr',
       'merchant_name', 'merchant_category', 'transaction_type', 'city',
       'hour_of_day', 'day_of_week', 'is_international', 'velocity_flag',
       'geo_anomaly_flag', 'high_amount_flag', 'fraud_label', 'fraud_reason'],
      dtype='str')

In [11]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     2000 non-null   str
 1   account_id         2000 non-null   str
 2   timestamp          2000 non-null   str
 3   amount_inr         2000 non-null   float64
 4   merchant_name      2000 non-null   str
 5   merchant_category  2000 non-null   str
 6   transaction_type   2000 non-null   str
 7   city               2000 non-null   str
 8   hour_of_day        2000 non-null   int64
 9   day_of_week        2000 non-null   str
 10  is_international   2000 non-null   str
 11  velocity_flag      2000 non-null   str
 12  geo_anomaly_flag   2000 non-null   str
 13  high_amount_flag   2000 non-null   str
 14  fraud_label        2000 non-null   int64
 15  fraud_reason       244 non-null    str
dtypes: float64(1), int64(2), str(13)
memory usage: 419.1 KB

In [12]:
transactions.isnull().sum()

transaction_id          0
account_id              0
timestamp               0
amount_inr              0
merchant_name           0
merchant_category       0
transaction_type        0
city                    0
hour_of_day             0
day_of_week             0
is_international        0
velocity_flag           0
geo_anomaly_flag        0
high_amount_flag        0
fraud_label             0
fraud_reason         1756
dtype: int64

In [13]:
transactions["fraud_label"].value_counts()

fraud_label
0    1756
1     244
Name: count, dtype: int64

In [14]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

In [15]:
from src.preprocessing import clean_text

In [16]:
sample = "I see a transaction of ₹10,000 I didn't make"

print("Original:")
print(sample)

print("\nProcessed:")
print(clean_text(sample))

Original:
I see a transaction of ₹10,000 I didn't make

Processed:
i see a transaction of <amount> i didn't make

In [17]:
#Build the Intent Classifier

In [18]:
##Import ML libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

In [19]:
##Prepare the data
X = tickets["query_text"].apply(clean_text)
y = tickets["category"]

In [20]:
print(X.head())
print(y.value_counts())

0    i see a transaction of <amount> i didn't make ...
1    i see a transaction of <amount> i didn't make ...
2    i see a transaction of <amount> i didn't make ...
3    i see a transaction of <amount> i didn't make ...
4    i see a transaction of <amount> i didn't make ...
Name: query_text, dtype: str
category
Fraud/Unauthorized    50
Loan                  50
KYC                   50
Account Access        50
Name: count, dtype: int64

In [21]:
#Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [22]:
# Create NLP Pipeline
intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2)
    )),
    ("classifier", LogisticRegression(
        max_iter=1000
    ))
])

In [23]:
# Train the model
intent_model.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
                ('classifier', LogisticRegression(max_iter=1000))])

In [24]:
# Evaluate the model
y_pred = intent_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [25]:
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

    Account Access       1.00      1.00      1.00        10
Fraud/Unauthorized       1.00      1.00      1.00        10
               KYC       1.00      1.00      1.00        10
              Loan       1.00      1.00      1.00        10

          accuracy                           1.00        40
         macro avg       1.00      1.00      1.00        40
      weighted avg       1.00      1.00      1.00        40

In [26]:
query = "I see a transaction I did not make"

prediction = intent_model.predict(
    [clean_text(query)]
)

print("Query:", query)
print("Predicted Intent:", prediction[0])

Query: I see a transaction I did not make
Predicted Intent: Fraud/Unauthorized

In [27]:
query = "My loan application is still pending"

print(
    intent_model.predict(
        [clean_text(query)]
    )[0]
)

Loan

In [28]:
query = "My KYC verification has failed"

print(
    intent_model.predict(
        [clean_text(query)]
    )[0]
)

KYC

In [29]:
# Accuracy is 100% .Evaluating it
feature_names = intent_model.named_steps["tfidf"].get_feature_names_out()

print("Number of TF-IDF features:", len(feature_names))

print(feature_names[:50])

Number of TF-IDF features: 479
['aadhaar' 'aadhaar due' 'aadhaar update' 'account' 'account but'
 'account don' 'account holder' 'account is' 'account kyc'
 'account marked' 'add' 'add my' 'address' 'address but' 'after'
 'after aadhaar' 'ago' 'ago and' 'agreed' 'ahmedabad' 'amount' 'amount by'
 'amount didn' 'amount from' 'amount is' 'amount not' 'amount on'
 'amount was' 'an' 'an atm' 'an education' 'an otp' 'an unknown' 'and'
 'and can' 'and heard' 'app' 'application' 'application rejected'
 'application tkt128276' 'application tkt593152' 'application tkt904150'
 'application tkt979995' 'applied' 'applied for' 'approved' 'approved but'
 'apr' 'apr number' 'are']

In [30]:
ngram_range=(1, 2)

In [31]:
test_queries = [
    "There is a payment on my statement that I never authorized",
    "Someone appears to have used my debit card",
    "Can you tell me where my borrowing request stands?",
    "The identity check on my account is not going through",
    "I cannot sign into my banking account"
]

for query in test_queries:
    prediction = intent_model.predict([clean_text(query)])[0]
    print(f"{query}")
    print(f"  → {prediction}\n")

There is a payment on my statement that I never authorized
  → Fraud/Unauthorized

Someone appears to have used my debit card
  → Fraud/Unauthorized

Can you tell me where my borrowing request stands?
  → Loan

The identity check on my account is not going through
  → KYC

I cannot sign into my banking account
  → Account Access

In [32]:
for query in test_queries:
    processed_query = clean_text(query)

    probabilities = intent_model.predict_proba([processed_query])[0]
    classes = intent_model.classes_

    best_index = probabilities.argmax()

    print("Query:", query)
    print("Prediction:", classes[best_index])
    print("Confidence:", round(probabilities[best_index], 3))
    print()

Query: There is a payment on my statement that I never authorized
Prediction: Fraud/Unauthorized
Confidence: 0.496

Query: Someone appears to have used my debit card
Prediction: Fraud/Unauthorized
Confidence: 0.473

Query: Can you tell me where my borrowing request stands?
Prediction: Loan
Confidence: 0.289

Query: The identity check on my account is not going through
Prediction: KYC
Confidence: 0.335

Query: I cannot sign into my banking account
Prediction: Account Access
Confidence: 0.454

In [33]:
#prepare data
X = tickets["query_text"].apply(clean_text)
y = tickets["category"]

#Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Create model
intent_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2)
    )),
    ("classifier", LogisticRegression(
        max_iter=1000
    ))
])

# train the model
intent_model.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
                ('classifier', LogisticRegression(max_iter=1000))])

In [34]:
query = "There is a payment on my statement that I never authorized"

processed_query = clean_text(query)

probabilities = intent_model.predict_proba([processed_query])[0]
classes = intent_model.classes_

print("Classes:")
print(classes)

print("\nProbabilities:")
print(probabilities)

print("\nClass + Probability:")

for class_name, probability in zip(classes, probabilities):
    print(f"{class_name}: {probability:.4f}")

Classes:
['Account Access' 'Fraud/Unauthorized' 'KYC' 'Loan']

Probabilities:
[0.16825015 0.49643144 0.17669372 0.15862469]

Class + Probability:
Account Access: 0.1683
Fraud/Unauthorized: 0.4964
KYC: 0.1767
Loan: 0.1586

In [35]:
#First check our embedding package
import sentence_transformers

print(sentence_transformers.__version__)

from sentence_transformers import SentenceTransformer

c:\Users\HopePraises\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

6.1.0

In [36]:
#Load an embedding model
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1778.03it/s]

In [37]:
#Generate Embeddings
text = "I didn't authorize this transaction"

embedding = embedding_model.encode(text)

print("Embedding shape:", embedding.shape)

print(embedding[:10])

Embedding shape: (384,)
[ 0.10069462  0.08297043 -0.01755879  0.04283746  0.01065407 -0.07595822
  0.09589755 -0.02629296  0.03861462  0.01176775]

In [38]:
#Compare Meanings:

sentences = [
    "I didn't authorize this transaction",
    "Someone used my card without permission",
    "What is the status of my loan application?",
    "My KYC verification is pending"
]

embeddings = embedding_model.encode(sentences)

print("Shape:", embeddings.shape)

Shape: (4, 384)

In [39]:
# Cosine Similarity

from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(embeddings)

print(similarity_matrix)

[[0.9999999  0.42719063 0.2513736  0.3275218 ]
 [0.42719063 1.         0.0991067  0.20774674]
 [0.2513736  0.0991067  1.         0.28547102]
 [0.3275218  0.20774674 0.28547102 1.        ]]

In [40]:
from pathlib import Path

policy_path = Path("../data/files/fraud_handling_policy.txt")

text = policy_path.read_text(encoding="utf-8")

print(text)

FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer request, within 30 minutes.
4.3 Provisional Credit: Within 10 working days for CNP fraud.
4.4 Investigation completion: 30-45 working days.
4.5 Final Resolution: Refund or rejection notice within 45 working days.

5. RISK CLASSIFICATION
HIGH RISK — Immediate escalation required:
  - Transaction amount > ₹50,000
  - Multiple fraudulent transactions
  - Suspected SIM swap or phishing
  - Cross-border fraudulent transactions
  - Account takeover attempt

MEDIUM RISK — Senior agent review:
  - Transaction amount ₹10,000–₹50,000
  - Single unauthorized recurring charge
  - Merchant dispute

LOW RISK — Standard agent handling:
  - Transaction amount < ₹10,000
  - Suspected duplicate charge
  - Subscription dispute

6. MANDATORY ACTIONS FOR HIGH-RISK CASES
6.1 Block all payment instruments immediately.
6.2 Reset net banking and mobile banking credentials.
6.3 Notify fraud risk team within 1 hour.
6.4 File SAR (Suspicious Activity Report) with FIU-IND if amount > ₹5L.
6.5 Preserve all logs and transaction records for 7 years.
6.6 Initiate chargeback with acquiring bank within 24 hours for card fraud.

7. CHARGEBACK PROCESS
7.1 First Presentment: Bank sends dispute to merchant's acquirer.
7.2 Merchant Response: Merchant has 30 days to respond.
7.3 Pre-Arbitration: If merchant rejects, bank files pre-arbitration.
7.4 Arbitration: Final resolution by card network (Visa/Mastercard/RuPay).

8. CUSTOMER COMMUNICATION STANDARDS
8.1 Acknowledge within 1 working hour.
8.2 Provide unique complaint reference number.
8.3 Update customer every 7 days on investigation progress.
8.4 Never ask customer to share OTP, PIN, or CVV over phone or email.
8.5 Use empathetic language; customer is a victim.

9. REGULATORY COMPLIANCE
9.1 RBI Master Direction on Limiting Liability of Customers (2017) applies.
9.2 All fraud cases > ₹1 crore to be reported to RBI within 24 hours.
9.3 Quarterly fraud MIS to be submitted to Board Risk Committee.

In [41]:
print("Characters:", len(text))

Characters: 3236

In [42]:
print("Words:", len(text.split()))

Words: 468

In [43]:
#Chunking 
def chunk_text(text, chunk_size=500, overlap=100):
    chunks = []

    start = 0

    while start < len(text):
        end = start + chunk_size

        chunk = text[start:end]
        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

In [44]:
chunks = chunk_text(text)

print("Number of chunks:", len(chunks))

Number of chunks: 9

In [45]:
##Display first 3 chunks
for i, chunk in enumerate(chunks[:3]):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk)

--- Chunk 1 ---
FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

--- Chunk 2 ---
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

--- Chunk 3 ---
24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [46]:
import sys
from pathlib import Path

project_root = Path.cwd().parent

sys.path.insert(0, str(project_root))

print("Project root:", project_root)

Project root: d:\AI_Projects\Banking Support & Fraud Intelligence System

In [47]:
# Using RAG
#Read the document
from src.rag import load_document, chunk_text
print("rag.py imported successfully")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 916.97it/s]

rag.py imported successfully

In [48]:
#Load the fraud policy
policy_path = "../data/files/fraud_handling_policy.txt"

text = load_document(policy_path)

print("Characters:", len(text))

Characters: 3236

In [49]:
#cREATE CHUNK DETAILS
chunks = chunk_text(
    text,
    chunk_size=500,
    overlap=100
)

print("Number of chunks:", len(chunks))

Number of chunks: 9

In [50]:
#cREATE EMBEDDINGS
from src.embedding import embed_texts

chunk_embeddings = embed_texts(chunks)

print("Embedding shape:", chunk_embeddings.shape)

Embedding shape: (9, 384)

In [51]:
#cOSINE SIMILARITY
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(
    [chunk_embeddings[0]],
    [chunk_embeddings[1]]
)

print("Similarity:", similarity[0][0])

Similarity: 0.6193754

In [52]:
import faiss

print(faiss.__version__)

1.14.3

In [53]:
#import retriever
from src.retriever import build_index, search_index

In [54]:
#Build FAISS index
chunk_embeddings
index = build_index(chunk_embeddings)

print("Number of vectors:", index.ntotal)

Number of vectors: 9

In [55]:
query = "I see a transaction on my account that I did not authorize"

In [56]:
from src.embedding import embed_text

query_embedding = embed_text(query)

print("Query embedding shape:", query_embedding.shape)

Query embedding shape: (384,)

In [57]:
#Search FAISS
scores, indices = search_index(
    index,
    query_embedding,
    top_k=3
)

print("Scores:", scores)
print("Indices:", indices)

Scores: [0.32353884 0.30440518 0.29240113]
Indices: [1 0 2]

In [58]:
# Retrieve Policy Text

for rank, (score, index_number) in enumerate(
    zip(scores, indices),
    start=1
):
    print(f"\n--- Result {rank} ---")
    print("Similarity:", round(float(score), 4))
    print("Chunk index:", index_number)
    print(chunks[index_number])

--- Result 1 ---
Similarity: 0.3235
Chunk index: 1
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

--- Result 2 ---
Similarity: 0.3044
Chunk index: 0
FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

--- Result 3 ---
Similarity: 0.2924
Chunk index: 2
24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [59]:
import importlib
import src.rag

importlib.reload(src.rag)

In [60]:
from src.rag import load_document, chunk_text, retrieve_context
from src.embedding import embed_texts
from src.retriever import build_index

In [61]:
policy_path = "../data/files/fraud_handling_policy.txt"

text = load_document(policy_path)

print("Characters:", len(text))

Characters: 3236

In [62]:
#Import Other functions
from src.embedding import embed_texts
from src.retriever import build_index

In [63]:
#Continue RAG pipeline
policy_path = "../data/files/fraud_handling_policy.txt"

text = load_document(policy_path)

chunks = chunk_text(
    text,
    chunk_size=500,
    overlap=100
)

print("Number of chunks:", len(chunks))

Number of chunks: 9

In [64]:
chunk_embeddings = embed_texts(chunks)

print("Embedding shape:", chunk_embeddings.shape)

Embedding shape: (9, 384)

In [65]:
index = build_index(chunk_embeddings)

print("Vectors in FAISS:", index.ntotal)

Vectors in FAISS: 9

In [66]:
#test retrieval
query = "I see a transaction on my account that I did not authorize"

results = retrieve_context(
    query,
    index,
    chunks,
    top_k=3
)

In [67]:
for rank, result in enumerate(results, start=1):

    print(f"\n========== Result {rank} ==========")
    print("Similarity:", round(result["score"], 4))
    print("Chunk index:", result["index"])
    print("\nPolicy:")
    print(result["chunk"])

========== Result 1 ==========
Similarity: 0.3235
Chunk index: 1

Policy:
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

========== Result 2 ==========
Similarity: 0.3044
Chunk index: 0

Policy:
FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

========== Result 3 ==========
Similarity: 0.2924
Chunk index: 2

Policy:
24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [68]:
#FAISS

query_embedding = embed_text(query)

scores, indices = search_index(
    index,
    query_embedding,
    top_k=3
)

In [69]:
from src.retriever import build_index, search_index

In [70]:
index = build_index(chunk_embeddings)

print("Vectors in FAISS:", index.ntotal)

Vectors in FAISS: 9

In [71]:
print("Scores:", scores)
print("Indices:", indices)

for rank, (score, index_number) in enumerate(
    zip(scores, indices),
    start=1
):
    print(f"\n========== Result {rank} ==========")
    print("Similarity:", round(float(score), 4))
    print("Chunk index:", index_number)
    print("\nPolicy:")
    print(chunks[index_number])

Scores: [0.32353884 0.30440518 0.29240113]
Indices: [1 0 2]

========== Result 1 ==========
Similarity: 0.3235
Chunk index: 1

Policy:
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

========== Result 2 ==========
Similarity: 0.3044
Chunk index: 0

Policy:
FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

========== Result 3 ==========
Similarity: 0.2924
Chunk index: 2

Policy:
24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [72]:
##LLM

context = "\n\n".join(
    result["chunk"]
    for result in results
)

print(context)

count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [73]:
print("USER QUERY:")
print(query)

print("\n\nRETRIEVED CONTEXT:")
print(context)

USER QUERY:
I see a transaction on my account that I did not authorize


RETRIEVED CONTEXT:
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

In [74]:
prompt = f"""
You are a banking customer-support assistant.

Answer the customer's query using ONLY the provided banking policy context.

If the context does not contain enough information, say:
"Insufficient information in the available policy."

Do not invent banking policies or procedures.

Customer Query:
{query}

Banking Policy Context:
{context}

Provide:
1. Customer Response
2. Risk Level
3. Suggested Next Action
"""

print(prompt)

You are a banking customer-support assistant.

Answer the customer's query using ONLY the provided banking policy context.

If the context does not contain enough information, say:
"Insufficient information in the available policy."

Do not invent banking policies or procedures.

Customer Query:
I see a transaction on my account that I did not authorize

Banking Policy Context:
count holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3 Card-Not-Present (CNP) Fraud: Online or MOTO transactions without physical card.
2.4 Account Takeover: Unauthorized access to customer banking credentials.

3. CUSTOMER REPORTING PROCESS
3.1 Customers must report unauthorized transactions within 72 hours via:
   - Toll-free helpline: 1800-XXX-XXXX (24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to n

FRAUD HANDLING POLICY — RETAIL BANKING
Version 3.2 | Effective: 01-Jan-2024
Issuing Authority: Chief Risk Officer

1. SCOPE
This policy applies to all unauthorized transactions, card fraud, UPI fraud, net banking fraud, and identity theft cases reported by retail banking customers.

2. DEFINITIONS
2.1 Unauthorized Transaction: Any debit from a customer account not initiated or authorized by the account holder.
2.2 Card-Present Fraud: Fraudulent transaction using physical card at POS or ATM.
2.3

24x7)
   - Mobile banking application → Report Fraud
   - Nearest branch
   - Written complaint to nodal officer
3.2 Zero Liability applies if customer reports within 3 working days of unauthorized transaction.
3.3 For delay of 4-7 days: Customer liability limited to ₹10,000.
3.4 Beyond 7 days: Customer liability as per transaction amount, subject to investigation.

4. BANK RESPONSE SLA
4.1 Acknowledgement: Within 1 working hour of complaint.
4.2 Card/Account Block: Immediately on customer reque

Provide:
1. Customer Response
2. Risk Level
3. Suggested Next Action

In [75]:
print(type(prompt))

<class 'str'>

In [76]:
import os

print(bool(os.getenv("GROQ_API_KEY")))

True

In [77]:
from src.llm import generate_response

print("Import successful")

Import successful

In [78]:
response = generate_response(prompt)

print(response)

**1. Customer Response**
We’re sorry to hear you’ve spotted an unauthorized transaction. As per our policy, you must report any unauthorized transaction within 72 hours (3 working days) to qualify for zero liability.

**2. Risk Level**
High – the transaction is not authorized by you and could indicate fraud or account takeover.

**3. Suggested Next Action**
- **Report immediately** by calling our toll‑free helpline (1800‑XXX‑XXXX, 24 x 7) or using the “Report Fraud” option in the mobile banking app.
- Request an **immediate block** of your card/account while the investigation is underway.
- Keep a record of the transaction details and any communication for reference.

Once you report, we’ll acknowledge your complaint within 1 working hour and begin the investigation.

In [89]:
from src.sentiment import analyze_sentiment

In [80]:
query = "I want to update my address."

result = analyze_sentiment(query)

print(result)

{'sentiment': 'Neutral', 'urgency': 'Low', 'urgency_score': 0}

In [ ]:
# Test Angry
query = "I have been trying to access my account for hours and I am extremely frustrated."

result = analyze_sentiment(query)

print(result)

{'sentiment': 'Negative', 'urgency': 'Medium', 'urgency_score': 1}

In [92]:
import inspect

print(inspect.getsource(analyze_sentiment))

]

In [108]:
# Fraud

query = "Someone made an unauthorized transaction from my account. Please block it immediately."

result = analyze_sentiment(query)

print(result)

{'sentiment': 'Neutral', 'urgency': 'High', 'urgency_score': 2}

In [100]:
query = "I have been trying to access my account for hours and I am extremely frustrated"

result = analyze_sentiment(query)

print(result)

{'sentiment': 'Negative', 'urgency': 'Medium', 'urgency_score': 1}

In [96]:
query = "Someone made an unauthorized transaction from my account. Please block it immediately."

negative_words = [
    "angry",
    "frustrated",
    "frustrating",
    "terrible",
    "worst",
    "upset",
    "scared",
    "worried",
    "hacked",
    "stolen",
    "fraud",
    "unauthorized",
    "blocked",
    "locked"
]

In [97]:
negative_found = any(
    word in query.lower()
    for word in negative_words
)

print("negative_found =", negative_found)

negative_found = True

In [104]:
import src.sentiment as sentiment

print("Loaded file:")
print(sentiment.__file__)

Loaded file:
d:\AI_Projects\Banking Support & Fraud Intelligence System\src\sentiment.py

In [106]:
import importlib
import src.sentiment as sentiment

importlib.reload(sentiment)

In [107]:
print(sentiment.NEGATIVE_WORDS)

['angry', 'frustrated', 'frustrating', 'terrible', 'worst', 'upset', 'scared', 'worried', 'hacked', 'stolen', 'fraud', 'unauthorized', 'blocked', 'locked']

In [109]:
query = "Someone made an unauthorized transaction from my account. Please block it immediately."

result = sentiment.analyze_sentiment(query)

print(result)

{'sentiment': 'Negative', 'urgency': 'High', 'urgency_score': 2}

In [110]:
#Risk
from src.risk import classify_risk

In [111]:
risk = classify_risk(
    intent="Fraud/Unauthorized",
    urgency="High"
)

print(risk)

High

In [112]:
risk = classify_risk(
    intent="Account Access",
    urgency="High"
)

print(risk)

Medium

In [113]:
risk = classify_risk(
    intent="Loan",
    urgency="Low"
)

print(risk)

Medium

In [114]:
risk = classify_risk(
    intent="General",
    urgency="Low"
)

print(risk)

Low

In [115]:
###ACTION

from src.action import recommend_action

In [116]:
actions = recommend_action(
    intent="Fraud/Unauthorized",
    risk="High"
)

print(actions)

['Report unauthorized transaction', 'Block card/account', 'Escalate for fraud investigation']

In [ ]:
#Test Loan
actions = recommend_action(
    intent="Loan",
    risk="Medium"
)

print(actions)

['Review loan application status', 'Request additional information if required']

In [118]:
#Test General
actions = recommend_action(
    intent="General",
    risk="Low"
)

print(actions)

['Provide standard customer support']